version: "2"

x-base: &base
  build:
    dockerfile: Dockerfile
  environment:
    REGISTRY_EXTERNAL_PORT: ${REGISTRY_EXTERNAL_PORT}
    REGISTRY_INTERNAL_PORT: ${REGISTRY_INTERNAL_PORT}
    REGISTRY_SERVICE_NAME: registry
    REGISTRY_API: ${HOST_PROTOCOL}://${HOST_IP}:${REGISTRY_EXTERNAL_PORT}
    HOST_PROTOCOL: ${HOST_PROTOCOL}
    HOST_IP: ${HOST_IP}
  networks:
    - frontend-compose-network

services:

  registry:
    extends:
      file: ./services/registry/docker-compose.yml
      service: app
    container_name: registry
    <<: *base
    build: 
      context: ./services/registry
    image: services/registry

  root-app:
    extends:
      file: ./services/root-app/docker-compose.yml
      service: app
    container_name: root-app
    <<: *base
    build: 
      context: ./services/root-app
    image: services/root-app
    depends_on:
      - registry

  root-menu:
    extends:
      file: ./services/root-menu/docker-compose.yml
      service: app
    container_name: root-menu
    <<: *base
    build: 
      context: ./services/root-menu
    image: services/root-menu
    depends_on:
      - registry

  app-a:
    extends:
      file: ./services/app-a/docker-compose.yml
      service: app
    container_name: app-a
    <<: *base
    build: 
      context: ./services/app-a
    image: services/app-a
    depends_on:
      - registry

  app-b:
    extends:
      file: ./services/app-b/docker-compose.yml
      service: app
    container_name: app-b
    <<: *base
    build: 
      context: ./services/app-b
    image: services/app-b
    depends_on:
      - registry

  app-c:
    extends:
      file: ./services/app-c/docker-compose.yml
      service: app
    container_name: app-c
    <<: *base
    build: 
      context: ./services/app-c
    image: services/app-c
    depends_on:
      - registry

  app-d:
    extends:
      file: ./services/app-d/docker-compose.yml
      service: app
    container_name: app-d
    <<: *base
    build: 
      context: ./services/app-d
    image: services/app-d
    depends_on:
      - registry
  
networks: 
  frontend-compose-network:
    driver: bridge